# Generated by Django 3.2.3 on 2021-05-24 20:16

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Typer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('nick', models.CharField(default='', max_length=16, unique=True)),
                ('host', models.CharField(default='', max_length=50, unique=True)),
                ('record', models.FloatField(default=0, max_length=6)),
                ('guest_can_pause', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
