# Generated by Django 3.2.3 on 2021-05-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Typer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=16, unique=True)),
                ('record', models.FloatField(max_length=6)),
            ],
        ),
    ]
