# Generated by Django 3.2.3 on 2021-06-12 18:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary', models.IntegerField(default=1)),
                ('text', models.CharField(default='Тут має бути текст', max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Typer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('nick', models.CharField(default='', max_length=16)),
                ('host', models.CharField(default='', max_length=50, unique=True)),
                ('guest_can_pause', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(default=api.models.getText, max_length=999)),
            ],
        ),
    ]
