# Generated by Django 3.2.3 on 2021-06-12 20:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(default='GUEST', max_length=8)),
                ('username', models.CharField(default=api.models.generate_nickname, max_length=16)),
                ('host', models.CharField(default='', max_length=50, unique=True)),
                ('password', models.CharField(default='password', max_length=16)),
            ],
        ),
    ]
