# Generated by Django 3.2.4 on 2021-06-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_typer_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='typer',
            name='text',
            field=models.CharField(default='Тут був текст', max_length=999),
        ),
        migrations.AlterField(
            model_name='typer',
            name='nick',
            field=models.CharField(default='', max_length=16),
        ),
    ]
