# Generated by Django 3.2.3 on 2021-06-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210611_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('vocabulary', models.IntegerField(default=1)),
                ('text', models.CharField(default='Тут має бути текст', max_length=999)),
            ],
        ),
        migrations.RemoveField(
            model_name='typer',
            name='text',
        ),
    ]
