# Generated by Django 3.2.3 on 2021-06-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210611_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='typer',
            name='text',
            field=models.CharField(default='Can you feel my heart?', max_length=999),
        ),
    ]
