# Generated by Django 3.2.3 on 2021-06-11 19:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_typer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typer',
            name='text',
            field=models.CharField(default=api.models.getText, max_length=999),
        ),
    ]
