# Generated by Django 3.2.3 on 2021-06-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_typer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
